# Generated by Django 2.2.3 on 2019-08-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='in_menus',
        ),
    ]
