# Generated by Django 2.2.3 on 2019-08-04 12:01

from django.db import migrations
import simplifytour.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_package_in_menus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adventurouspackage',
            options={'ordering': ('_order',), 'verbose_name': 'Adventurous Package', 'verbose_name_plural': 'Adventurous Packages'},
        ),
        migrations.AlterModelOptions(
            name='trekpackage',
            options={'ordering': ('_order',), 'verbose_name': 'Trekking Package', 'verbose_name_plural': 'Trekking Packages'},
        ),
        migrations.AddField(
            model_name='package',
            name='_order',
            field=simplifytour.core.fields.OrderField(null=True, verbose_name='Order'),
        ),
    ]
